### ISSUE TITLE
ModuleNotFoundError: No module named 'e4e.models'

### ISSUE THREAD

**Issue by johndpope** [gyupro/streamlit_JoJoGAN#1]
I looked into e4e folder and pasted in the models directory with e4e_ffhq_encode.pt file but then I get 

    from e4e_projection import projection as e4e_projection
  File "/home/oem/Documents/gitWorkspace/streamlit_JoJoGAN/e4e_projection.py", line 8, in <module>
    from e4e.models.psp import pSp
ModuleNotFoundError: No module named 'e4e.models'

ImportError: cannot import name 'projection' from 'e4e_projection' (/home/oem/Documents/gitWorkspace/streamlit_JoJoGAN/e4e_projection.py)
2022-08-29 13:30:08.276 Uncaught app exception
Traceback (most recent call last):
  File "/home/oem/miniconda3/envs/ldm/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "/home/oem/Documents/gitWorkspace/streamlit_JoJoGAN/streamlit_jojogan.py", line 26, in <module>
    from e4e_projection import projection as e4e_projection
ImportError: cannot import name 'projection' from 'e4e_projection' (/home/oem/Documents/gitWorkspace/streamlit_JoJoGAN/e4e_projection.py)
^Z

**Comment by gyupro** [comment]
Hi there, I omitted some files while excluding the models folder by .gitignore. I added files, you should be fine by pulling it again and installing some required libraries (pip install ninja, streamlit and so on)

**Comment by johndpope** [comment]
thank you - I'll give it a try later.

**Comment by johndpope** [comment]
thanks - it's all working. 

seems like - all these could be also added from 
https://github.com/kaz12tech/JoJoGAN/blob/main/demo.py

    "stylegan2-ffhq-config-f.pt": "1Yr7KuD959btpmcKGAUsbAk5rPjX2MytK",
    "e4e_ffhq_encode.pt": "1o6ijA3PkcewZvwJJ73dJ0fxhndn0nnh7",
    "restyle_psp_ffhq_encode.pt": "1nbxCIVw9H3YnQsoIPykNEFwWJnHVHlVd",
    "arcane_caitlyn.pt": "1gOsDTiTPcENiFOrhmkkxJcTURykW1dRc",
    "arcane_caitlyn_preserve_color.pt": "1cUTyjU-q98P75a8THCaO545RTwpVV-aH",
    "arcane_jinx_preserve_color.pt": "1jElwHxaYPod5Itdy18izJk49K1nl4ney",
    "arcane_jinx.pt": "1quQ8vPjYpUiXM4k1_KIwP4EccOefPpG_",
    "arcane_multi_preserve_color.pt": "1enJgrC08NpWpx2XGBmLt1laimjpGCyfl",
    "arcane_multi.pt": "15V9s09sgaw-zhKp116VHigf5FowAy43f",
    "disney.pt": "1zbE2upakFUAx8ximYnLofFwfT8MilqJA",
    "disney_preserve_color.pt": "1Bnh02DjfvN_Wm8c4JdOiNV4q9J7Z_tsi",
    "jojo.pt": "13cR2xjIBj8Ga5jMO7gtxzIJj2PDsBYK4",
    "jojo_preserve_color.pt": "1ZRwYLRytCEKi__eT2Zxv1IlV6BGVQ_K2",
    "jojo_yasuho.pt": "1grZT3Gz1DLzFoJchAmoj3LoM9ew9ROX_",
    "jojo_yasuho_preserve_color.pt": "1SKBu1h0iRNyeKBnya_3BBmLr4pkPeg_L",
    "supergirl.pt": "1L0y9IYgzLNzB-33xTpXpecsKU-t9DpVC",
    "supergirl_preserve_color.pt": "1VmKGuvThWHym7YuayXxjv0fSn32lfDpE",
    "art.pt": "1a0QDEHwXQ6hE_FcYEyNMuv5r5UnRQLKT",
